baseURL = "http://www.nathanmyles.ca"

title = "Nathan Myles"
languageCode = "en-us"
defaultContentLanguage = "en"

[permalinks]
posts = "/posts/:filename"

[params]
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006"

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/"
name = "Welcome"
weight = 1

[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 2

[[menu.main]]
url = "/resume/"
name = "Resume"
weight = 3

[[menu.main]]
url = "/contact/"
name = "Contact"
weight = 4

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/resume/"
name = "Resume"
weight = 2

[[menu.foot]]
url = "/contact/"
name = "Contact"
weight = 3

[languages]
[languages."en"]
weight = 1
languageName = "English"