name: 'Site Deployer'
description: 'Build a hugo blog, and deploy it'
inputs:
  user:
    description: 'deploy user'
    required: true
  server_url:
    description: 'deploy location'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.server_url }}