name: 'Site Deployer'
description: 'Build a hugo blog, and deploy it'
inputs:
  user:
    description: 'deploy user'
    required: true
    default: 'u52708221-nmyles-dev'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}