name: CI-DEV

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so tbe job can access it
      - uses: actions/checkout@v2

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          user: ${{ secrets.SSHPASS_NMYLES_DEV_USER }}
          server_url: ${{ secrets.NMYLES_SERVER_URL }}
        env:
          SSHPASS: ${{ secrets.SSHPASS_NMYLES_DEV }}